version: '2'
services:
#  apiserver:
#    restart: always
#    image: akka-http-rest:1.0.0
#    ports:
#      - 80:9000
#    environment:
#      APP_SECRET: "some-secret-value"
#      JDBC_URL: "jdbc:postgres://postgres:5432/postgres"
#      JDBC_USER: "postgres"
#      JDBC_PASSWORD: "postgres"
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
